version: "3.8"
services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432


  springboot-app:
    build: .
    container_name: my_springboot_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
        - 8080:8080


volumes:
  pgdata: